### ISSUE TITLE
nixos-rebuild no longer works

### ISSUE THREAD

**Issue by yshui** [ners/nix-monitored#7]
`nixos-rebuild` runs `nix --extra-experimental-features 'nix-command flakes' build`. I would expect `nix-monitored` to remove `--extra-experimental-features` and run `nom build` but it didn't.

I think it was broken by https://github.com/ners/nix-monitored/commit/f4abdaf9c69044492b27d70be7315575ce300384

**Comment by ners** [comment]
Thanks for reporting the issue! Can you check if it was fixed in https://github.com/ners/nix-monitored/commit/42716246502d3aef15f598f9af27479665df13d7?

**Comment by campbellcole** [comment]
I'm trying to check but I can't rebuild my system at all. How might I bypass the nix-monitored binary?

Edit: spoke too soon. `nix shell nixpkgs#nixos-rebuild` provided the unmodified version. Checking the fix now.

Edit 2: Checked and it worked for me.

**Comment by ners** [comment]
`nix-monitored` can also be bypassed by setting the environment variable `NIX_MONITOR=disable`, in which case it will pass all the args untouched to the underlying Nix package.
